### ISSUE TITLE
Are sensor data exported from movebank always sorted by timestamp?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-for-biologging#31]
@sarahcd can we assume that sensor data exported from Movebank are always sorted by timestamp? This would cut down on processing for Darwin Core.

**Comment by sarahcd** [comment]
yes, by ID and by timestamp, I can't think of any exceptions.

**Comment by peterdesmet** [comment]
What ID exactly?

**Comment by sarahcd** [comment]
update: Event data downloaded from Movebank are ordered by tag_id, deploy_on_timestamp, deployment_id, and by timestamp within each of those groups. The tag_id and deployment_id are internal database identifiers rather than user-assigned identifiers, so it's not very useful. If you have suggestions of other ordering that would work well for DwC processing, let me know and I can discuss possible updates with our team.

**Comment by peterdesmet** [comment]
Ok, good. Most important aspect is that records are sorted chronologically by timestamp within those groups, so we don't have to resort when transforming for DwC (see e0909dd).
