### ISSUE TITLE
Should sex, lifeStage, ... be extended to gps records

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-for-biologging#32]
At deployment, one often determines the sex, lifeStage and reproductive condition of the animal. Should these values be assigned to the gps records as well?

- sex: unlikely to change for animals that are gps tagged?
- lifeStage: changes over time, until it is `adult`
- reproductiveCondition: definitely can change over time

Anyone?

**Comment by albenson-usgs** [comment]
My opinion is that these values should not be included in the GPS records. Unless this information is collected by the GPS somehow? I don't think it is but I'm also not an expert in this data. Yes sex is unlikely to change but it's also not being recorded by the GPS. With lifeStage and reproductiveCondition we would have no way of knowing because this is not recorded by the sensors (right?). Maybe this would also help distinguish the human observation from the machine observations?

**Comment by peterdesmet** [comment]
I think I agree @albenson-usgs 👍

**Comment by sarahcd** [comment]
I agree @albenson-usgs! For analysis people sometimes want to assign age and reproductive condition on GPS data, but this is variable across taxa or even the specific analysis, and not something the sensors are recording directly, so I would leave this job to the user. Note that Euromammals does have a way of automatically 'aging' animals based on the age at deployment, I think owners provide the estimated year/date of birth.
